name: Sync to Hugging Face hub
on:
  push:
    branches:
      - main
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Sync to Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          huggingface_repo_id: 'soumitsr/parrotbox'
          github_repo_id: 'soumitsalman/parrotbox'
          hf_token: ${{ secrets.HUGGINGFACE_TOKEN }}
          repo_type: 'space'  # Can be 'model', 'dataset', or 'space'
